.gitignore
static/app.js

Set resolution to support retina display

---

Dockerfile
README.rst
app.py
requirements.txt

Allow configuring multiple clusters via `CLUSTERS` env var.

Multi cluster

---

app.py
app/src/cluster.js
app/src/node.js
examples/unassigned-pod.yaml

Also draw unassigned/pending pods.

Draw unassigned pods / colorize bars

---

app/src/node.js

Fix parsing of Kubernetes resource units (see https://github.com/kubernetes/kubernetes/blob/master/docs/design/resources.md).

Fix parsing of resource unit suffixes (Mi/Gi/..)

---

app.py
app/webpack.config.js
templates/index.html

Cache busting for production..

hash JS bundle for production

---

app.py

** WORK IN PROGRESS **
Support OAuth 2 redirect flow for UI login.

OAuth 2 Login

---

app.py

This is just a quickfix, we should check Skipper's `X-FORWARDED-FOR` headers instead.

quickfix for app behind Skipper/ALB

---

app.py
app/.eslintrc.yml
app/src/app.js
app/src/node.js
app/src/pod.js
app/webpack.config.js
templates/index.html

As a first step to interact with the app.

Interactive search (by pod name)

---

app/package.json
app/src/app.js
app/src/bars.js
app/src/node.js
app/src/pod.js
app/src/utils.js
app/webpack.config.js

please don't delete the branch

Tooltip for node bars

---

app/src/pod.js
deploy/deployment.yaml

#2 pods with non-ready containers are flashing green

---

app.py
app/src/app.js
app/src/cluster.js
app/src/node.js
app/src/pod.js

Animate pod

---

app/src/node.js
app/src/pod.js
app/src/utils.js

- Added pod metrics
- Increased the sharpness of pod names.

Add pod metrics

---

app/src/bars.js

added backing canvas for overall tooltip hit rate

added backing canvas for overall tooltip hit rate

---

app/src/app.js
app/src/cluster.js
app/src/colors.js

Add menubar

---

.gitignore
app.py
app/src/pod.js

#50 indicate pod restarts as red "ticks" and show number in tooltip

---

.travis.yml
app.py
app/src/app.js
app/src/node.js
app/src/pod.js

fix animation and de-register pods

---

app.py
app/src/app.js

#37 animate pod termination/deletion

---

app.py
app/src/app.js
app/src/cluster.js
app/src/pod.js

#66 allow filtering clusters (click on cluster title bar)

---

README.rst
app.py
app/src/app.js
app/src/cluster.js
deploy/deployment.yaml
deploy/redis-deployment.yaml
deploy/redis-service.yaml
requirements.txt

Use HTML5 EventSource and background API polling with memory or Redis as event bus.
Contributes to #49.

EventSource, background job and Redis pub/sub

---

app.py

#76 handle missing Heapster metrics

---

app.py
templates/screen-tokens.html

#65 allow creating and redeeming screen tokens

---

app.py

#79 handle TERM signal and wait 10 seconds

---

Makefile
deploy/deployment.yaml
kube_ops_view/cluster_discovery.py
kube_ops_view/kubernetes.py
kube_ops_view/main.py
requirements.txt

Allow running within a Kubernetes cluster without `kubectl proxy`.
Also prepares cluster discovery for #73

Incluster auth

---

README.rst
docs/multiple-clusters.rst
kube_ops_view/cluster_discovery.py
kube_ops_view/kubernetes.py
kube_ops_view/main.py
kube_ops_view/stores.py

#73 implement --cluster-registry-url option

---

README.rst
docs/multiple-clusters.rst
kube_ops_view/backoff.py
kube_ops_view/cluster_discovery.py
kube_ops_view/kubernetes.py
kube_ops_view/main.py
kube_ops_view/mock.py
kube_ops_view/update.py
kube_ops_view/utils.py
tests/test_mock.py

Kubeconfig & Backoff

---

app/src/app.js
app/src/cluster.js
app/src/selectbox.js
kube_ops_view/kubernetes.py
kube_ops_view/main.py
kube_ops_view/stores.py
kube_ops_view/update.py

Indicate unreachable clusters

---

app/package.json
app/webpack.config.js

Babel Polyfill for ECMAScript 2017

---

app/src/app.js
app/src/vendor/addWheelListener.js

Add support for panning via keyboard, mouse and touch events and zoom via mouse wheel.

Pan & Zoom

---

app/src/app.js

#108 add "reload" parameter

---

app/src/app.js

#108 add "dashboard" param to hide menu bar

---

app/src/app.js
kube_ops_view/main.py

#108 do not animate pod creation while bootstrapping

---

app/src/node.js
kube_ops_view/kubernetes.py

#114 hide completed jobs after one hour

---

app/src/app.js
docs/index.rst
docs/ui-options.rst

Add `scale` UI option

---

app/src/app.js
app/src/config.js
docs/ui-options.rst

#108 add `renderer` UI option to disable WebGL

---

app/src/pod.js

#103 assume empty pod name if undefined

---

kube_ops_view/kubernetes.py

#125 hide failed pods after one hour (same as completed jobs)

---

app/src/pod.js

#120 show pod namespace

---

kube_ops_view/kubernetes.py

#129 handle pods in strange error state

---

app/package.json
app/webpack.config.js

Bump JS versions

---

Dockerfile
Makefile
app/package-lock.json
app/package.json

Everybody loves :heart: bleeding-edge :hocho: versions (especially in the JS world).

bump dependency versions (node modules)

---

README.rst

Add run-locally instructions for MacOS

---

kube_ops_view/mock.py

I want to add support for searching by labels. This PR adds test labels in 'mock' mode.

Random pod labels in 'mock' mode

---

app/src/app.js
docs/user-guide.rst

Queries like `env=prod` will filter pods by label.
WebStorm did some autoformatting

Labels filtering

---

kube_ops_view/kubernetes.py
kube_ops_view/mock.py

fixes #157 
See issue for details

Filter out "Evicted" pods

---

kube_ops_view/cluster_discovery.py

Fixes #164 
Tested with Minikube.

#164 fix in-cluster config

---

app/package-lock.json
app/package.json

Ran `npm audit fix` and manual update.

fix NPM vulnerabilities

---

app/package-lock.json
app/src/pod.js
app/src/utils.js

This should fix #187.
Also compare to https://github.com/hjacobs/kube-resource-report/blob/master/kube_resource_report/report.py#L43

Fix resource parsing

---

app/package.json
app/src/app.js
app/src/pod.js

I also bumped pixi.js to 4.8.5

Add sorting by status

---

README.rst
docs/access-control.rst
kube_ops_view/main.py

Added support for scope and update docs. fixes #198

Add support for OAuth2 scope parameter

---

kube_ops_view/mock.py

With this, in `mock` mode we have information about `usage` on a node.
Link: https://media.giphy.com/media/2esZA9flijnTwz81Vc/source.mp4

Generate more real data

---

app/src/app.js
app/src/bars.js
app/src/cluster.js
app/src/node.js
kube_ops_view/mock.py

It is part of #6 issue. There is still a room for improvement, for instance we could put more clusters in a row.

Dynamic sizing nodes

---

.dockerignore
Dockerfile
Makefile
app/package-lock.json

* bump versions of used Docker images
* add [`.dockerignore`](https://docs.docker.com/engine/reference/builder/#dockerignore-file) to send only a fraction of data to the Docker daemon (`app` dir is huge)

update Docker base images

---

Pipfile
Pipfile.lock
docs/access-control.rst
kube_ops_view/cluster_discovery.py
kube_ops_view/kubernetes.py
kube_ops_view/main.py
kube_ops_view/oauth.py

Switch to pykube-ng

---

app/package-lock.json
app/package.json
app/src/themes.js

Playing around with new filters, check out the PixiJS Filters Demo: http://pixijs.io/pixi-filters/tools/demo/

add CRT filter

---

app/src/app.js
app/src/cluster.js

#229 Scale clusters properly

---

kube_ops_view/main.py

To be able to pass traffic through http proxies.
This is to disable caching/buffering of responses that breaks the connection.

Added missing http-headers

---

Makefile
app/package-lock.json
app/package.json

update npm dependencies
